version: '3.8'

services:
  app:
    build: .
    volumes:
      - ./:/app           # Mount entire project directory (includes SQLite DB)
      - static_data:/app/staticfiles  # Persistent static files
      - media_data:/app/media         # Persistent media files
    environment:
      - DEBUG=False
    expose:
      - "8000"
    restart: unless-stopped

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/staticfiles:ro  # Nginx only needs read access
      - media_data:/app/media:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_data:
  media_data: