version: '3.8'

services:
  app:
    build:
      context: .
      args:
        USER_ID: ${UID:-1000}  # Pass host user ID
        GROUP_ID: ${GID:-1000}
    volumes:
      - ./:/app
      - static_data:/app/staticfiles
      - media_data:/app/media
    environment:
      - DEBUG=False
      - PYTHONUNBUFFERED=1
    expose:
      - "8000"
    restart: unless-stopped
    user: "${UID:-1000}:${GID:-1000}"  # Run as host user

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_data:/app/staticfiles:ro
      - media_data:/app/media:ro
    depends_on:
      - app
    restart: unless-stopped

volumes:
  static_data:
  media_data: