# Generated by Django 5.2.4 on 2025-10-26 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_groups_alter_user_user_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('icon', models.CharField(default='fa-trophy', max_length=50)),
                ('achievement_type', models.CharField(choices=[('FIRST_PLAY', 'First Play'), ('SCORE_1000', 'Score 1000 Points'), ('TOP_10', 'Top 10 Player'), ('STREAK_MASTER', 'Streak Master'), ('ALL_GAMES', 'All Games Played'), ('GAME_WINNER', 'Game Winner')], max_length=50, unique=True)),
                ('requirement', models.IntegerField(help_text='Required value to unlock (e.g., 1000 for score, 10 for streak)')),
            ],
            options={
                'verbose_name': 'Achievement',
                'verbose_name_plural': 'Achievements',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='UserAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unlocked_at', models.DateTimeField(auto_now_add=True)),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.achievement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_achievements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-unlocked_at'],
                'unique_together': {('user', 'achievement')},
            },
        ),
    ]
