# Generated by Django 5.2.4 on 2025-07-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leaderboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaderboard',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
