# Generated by Django 5.2.4 on 2025-07-11 04:28

import games.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamescore',
            options={'ordering': ['-score'], 'verbose_name': 'Game Score', 'verbose_name_plural': 'Game Scores'},
        ),
        migrations.AddField(
            model_name='game',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload game cover image (optimal size: 800x600px)', null=True, upload_to=games.models.game_image_upload_path),
        ),
    ]
